name: base_app
description: A new Flutter project.
version: 1.0.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  micro_core:
  micro_app_login:
  micro_app_home:

dependency_overrides:
  micro_core:
    git:
      url: https://github.com/oliveira-gabriel/micro_core.git
      ref: v1.0.1

  micro_commons_design_system:
    git:
      url: https://github.com/oliveira-gabriel/micro_commons_design_system.git
      ref: v1.0.1

  micro_app_login:
    path: ../micro_app_login

  micro_app_home:
    path: ../micro_app_home

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
